package com.example.core.common_files.common_ui

enum class Routes {
    CREATETRAININGSCREEN,
    ENTRYSCREEN,
    SAVEDTRAININGSSCREEN,
    LISTOFEXERCISESSCREEN,
    TRAININGSCREEN,
    TRAININGRESULTSSCREEN,
    TRAININGRESULTSDETAILEDSCREEN
}